Enthought Python Distribution (EPD) free version -- www.enthought.com
Version: 7.3-2 (32-bit)
(type 'upgrade' or see www.enthought.com/epd/upgrade to get the full EPD)

Python 2.7.3 |EPD_free 7.3-2 (32-bit)| (default, Apr 12 2012, 11:28:34) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "credits", "demo" or "enthought" for more information.
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516uCr.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167Mx.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167Mx.py'
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516tWA.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165166gG.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516HrM.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516U1S.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516U1S.py", line 3, in <module>
    print date_parse('13:46:31 11-07-11')
NameError: name 'date_parse' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516h_Y.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516h_Y.py", line 6, in <module>
    print date_parse('13:46:31 11-07-11')
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516h_Y.py", line 4, in date_parse
    return(datetime.datetime.strptime(x, '%H:%M:%S %d-%m-%y'))
NameError: global name 'datetime' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516uJf.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167Tl.py...
['Experiment Started: 13:46:31 11-07-11 ']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Ier.py...
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Vox.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516HyA.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516U8G.py...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516U8G.py", line 4, in <module>
  File "practicecode.py", line 2
    Experiment started
                     ^
SyntaxError: invalid syntax
>>> >>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516hGN.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516hGN.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 2
    Experiment started
                     ^
SyntaxError: invalid syntax
>>>## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516uQT.py...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516uQT.py'
>>> >>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167aZ.py...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167aZ.py", line 4, in <module>
  File "practicecode.py", line 2
    Experiment started
                     ^
SyntaxError: invalid syntax
>>> >>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Ilf.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Ilf.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 2
    Experiment started
                     ^
SyntaxError: invalid syntax
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Vvl.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Vvl.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 1, in <module>
    Exp_intro = {'Experiment started': '13:46:31 11-07-11', 'subject': CSN1}
NameError: name 'CSN1' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516i5r.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vDy.py...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vDy.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 1, in <module>
    Exp_intro = {'Experiment started': '13:46:31 11-07-11', 'subject': CSN1}
NameError: name 'CSN1' is not defined
>>> >>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516hNB.py...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516hNB.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 4
    dictionary = ['Experiment started]
                                     ^
SyntaxError: EOL while scanning string literal
>>> >>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516uXH.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516uXH.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 4
    dictionary = ['Experiment started]
                                     ^
SyntaxError: EOL while scanning string literal
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167hN.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516IsT.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516V2Z.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516iAg.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vKm.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165168Us.py...
>>>   ^C ^C
KeyboardInterrupt
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Jfy.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165167oB.py...
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516IzH.py...
>>>   ^C ^C
KeyboardInterrupt
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516V9N.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516iHU.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516iHU.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 29, in <module>
    dictionary = {'Experiment started' : x, 'Subject': 'CSN1', 'Subject mass':'35.4g', 'measure time': '60 seconds', 'settle time': '144 seconds'}
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vRa.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165168bg.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Jmm.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
x
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Wws.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
x
CSN1
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516j6y.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
x
CSN1
['Subject mass', 'measure time', 'Experiment started', 'settle time', 'Subject']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516VEC.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
x
CSN1
['Subject mass', 'measure time', 'Experiment started', 'settle time', 'Subject']
['35.4g', '60 seconds', 'x', '144 seconds', 'CSN1']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516iOI.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516iOI.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 33, in <module>
    functionToCall = tokenDict[line]
NameError: name 'tokenDict' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vYO.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vYO.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 34, in <module>
    functionToCall()
TypeError: date_parse() takes exactly 1 argument (0 given)
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165168iU.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165168iU.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 29, in <module>
    dictionary = {'Experiment started' : date_parse(x), 'Subject':split , 'Subject mass':split, 'measure time': split, 'settle time': split}
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Jta.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Jta.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 4, in <module>
    print date_parse('13:46:31 11-07-11')
  File "practicecode.py", line 2, in date_parse
    return(datetime.datetime.strptime(x, '%H:%M:%S %d-%m-%y'))
NameError: global name 'datetime' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516W3g.py...
2011-07-11 13:46:31
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516W3g.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 8, in <module>
    dictionary = {'Experiment started' : date_parse, 'Subject':split , 'Subject mass':split, 'measure time': split, 'settle time': split}
NameError: name 'split' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516jBn.py...
2011-07-11 13:46:31
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516jBn.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 13, in <module>
    functionToCall()
TypeError: date_parse() takes exactly 1 argument (0 given)
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516wLt.py...
2011-07-11 13:46:31
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516wLt.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 14, in <module>
    functionToCall()
TypeError: date_parse() takes exactly 1 argument (0 given)
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169Vz.py...
2011-07-11 13:46:31
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169Vz.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 14, in <module>
    functionToCall()
TypeError: date_parse() takes exactly 1 argument (0 given)
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vfC.py...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516vfC.py'
## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165168pI.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165168pI.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 29
    dictionary = {'Experiment started' : '13:46:31 11-07-11', 'Subject': 'CSN1' , 'Subject mass':'35.4g', 'measure time': '60seconds', 'settle time': '144 seconds'}dictiondictionary['Experiment started']
                                                                                                                                                                                    ^
SyntaxError: invalid syntax
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516J0O.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516J0O.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 29
    dictionary = {'Experiment started' : '13:46:31 11-07-11', 'Subject': 'CSN1' , 'Subject mass':'35.4g', 'measure time': '60seconds', 'settle time': '144 seconds'}dictiondictionary['Subject']
                                                                                                                                                                                    ^
SyntaxError: invalid syntax
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516W-U.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516jIb.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516wSh.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169cn.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169cn.py'
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Knt.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Xxz.py...
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516J7C.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516J7C.py'
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516WFJ.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516WFJ.py", line 15
    For line in lines:
           ^
SyntaxError: invalid syntax
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516jPP.py...
i need a dictionary
None
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516wZV.py...
<function function1 at 0x492d30>
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169jb.py...
i need a dictionary
None
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Kuh.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Kuh.py", line 6, in <module>
    print function1(now)
NameError: name 'now' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516X4n.py...
<function function1 at 0x492ef0>
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516kCu.py...
<function function1 at 0x492cf0>
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xM0.py...
i need a dictionary
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516jWD.py...
i need a dictionary
i need a dictionary
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516wgJ.py...
2011-07-11 13:46:31
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516wgJ.py", line 4, in <module>
  File "practicecode.py", line 9, in <module>
    dictionary = {'Experiment started' : date_parse(), 'Subject':'n' , 'Subject mass':'n', 'measure time': 'n', 'settle time': 'n'}
TypeError: date_parse() takes exactly 1 argument (0 given)
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169qP.py...
2011-07-11 13:46:31
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169qP.py", line 4, in <module>
    reload(practicecode)
  File "practicecode.py", line 9, in <module>
    dictionary = {'Experiment started' : date_parse(x), 'Subject':'n' , 'Subject mass':'n', 'measure time': 'n', 'settle time': 'n'}
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516K1V.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516K1V.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516X_b.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516X_b.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516kJi.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516kJi.py", line 16
    return(datetime.datetime.strptime( , '%H:%M:%S %d-%m-%y'))
                                       ^
SyntaxError: invalid syntax
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xTo.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xTo.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516-du.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516-du.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Lo0.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Lo0.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python165169xD.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> 
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516K8J.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516XGQ.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516kQW.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516kQW.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xac.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xac.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516-ki.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516-ki.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Lvo.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Lvo.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Y5u.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Y5u.py", line 6, in <module>
    function1(x)
NameError: name 'x' is not defined
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516lD1.py...
i need a dictionary
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516XNE.py...
i need a dictionary
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516kXK.py...
i need a dictionary
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xhQ.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xhQ.py'
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516-rW.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516L2c.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516YAj.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
['CSN1']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516lKp.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
['144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516yUv.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516_e1.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516xoE.py...
['Experiment Started: 13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516-yK.py...
['Experiment Started', '13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516L9Q.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516L9Q.py", line 4, in <module>
    reload(parsing)
  File "parsing.py", line 26
    def parse_experiment_time(line)
                                  ^
SyntaxError: invalid syntax
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516YHX.py...
['Experiment Started', '13:46:31 11-07-11 ']
2011-07-11 13:46:31
['Subject: CSN1']
['subject mass: 35.4g']
['measure time: 60 seconds']
['settle time: 144 seconds']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516lRd.py...
['Experiment Started', '13:46:31 11-07-11 ']
2011-07-11 13:46:31
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516ybj.py...
>>> 
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516_lp.py...
>>> 
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Mwv.py...
['Subject', 'CSN1']
>>> ## executing temporary file /var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Z61.py...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/BQ/BQo4lc53FZmgd0vyfa2mOk+++TQ/-Tmp-/Python16516Z61.py", line 4, in <module>
  File "parsing.py", line 34, in <module>
    print parse_subject("Subject: CSN1")
  File "parsing.py", line 32, in parse_subject
    parse_line1 = {split[0] : split_line}
TypeError: 'function' object has no attribute '__getitem__'
>>> 